### ISSUE TITLE
memory get increased significantly every time when expanding the cell 

### ISSUE THREAD

**Issue by adaoli** [justinmfischer/SwiftyExpandingCells#1]
In the Demo the memory usage increases around 10 MB for each expanding. Any way to control the memory. Thanks.

**Comment by justinmfischer** [comment]
I'll run instruments and check the allocations. Thanks for the feedback, standby.

**Comment by antiquechrono** [comment]
I managed to fix the memory leak problem. You were calling UIGraphicsBeginImageContextWithOptions in SwiftyExpandingTransition.animateTransition() without calling UIGraphicsEndImageContext which never allowed the contexts to release memory. All you need to do is move the graphics context creation inside the if statement on line 41.

**Comment by justinmfischer** [comment]
Fixed in release 1.1 -Thanks @antiquechrono
