### ISSUE TITLE
Do you need the background view?

### ISSUE THREAD

**Issue by LutherBaker** [justinmfischer/SwiftyExpandingCells#2]
I notice things look the same if I comment out lines 104, 105, 110 and 131 in the transition implementation file [SwiftyExpandingTransition](https://github.com/justinmfischer/SwiftyExpandingCells/blob/master/SwiftyExpandingCells/Src/SwiftyExpandingTransition.swift). Is the "extra" background view really needed? If so, can you briefly elaborate on what you're using it for?

CMD-T slows the animations way down in the simulator ... but I couldn't see any visual difference.

Thanks!

**Comment by justinmfischer** [comment]
Yes, it is need to create a dark background for the transition. This color can be changed as needed.
