### ISSUE TITLE
Do you need to add the Source View?

### ISSUE THREAD

**Issue by LutherBaker** [justinmfischer/SwiftyExpandingCells#3]
Line 111 of [SwiftyExpandingTransition](https://github.com/justinmfischer/SwiftyExpandingCells/blob/master/SwiftyExpandingCells/Src/SwiftyExpandingTransition.swift) adds the **sourceView** to the view hierarchy. Is that intentional? Why wouldn't the **sourceView** already be there?

It continues to work if I comment out that line (is this possibly related to Issue #1)?

Thanks!

**Comment by justinmfischer** [comment]
Yes, it is used for calculations. Not related to issue #1
